
version: '2'
services:
  nodejs:
    build: .
    image: nikita_system_info_archlinux
    volumes:
      - ../../../../:/nikita
    environment:
      NIKITA_TEST_MODULE: /nikita/packages/system/env/info_archlinux/test.coffee
