
version: '2'
services:
  nodejs:
    build: .
    image: nikita_core_arch_chroot
    volumes:
      - ../../../../:/nikita
    environment:
      NIKITA_TEST_MODULE: /nikita/packages/core/env/arch_chroot/test.coffee
    cap_add:
      - SYS_ADMIN # Required to use `mount`
